language: generic

sudo: required

dist: trusty
os:
  - linux

env:
  - MPI_IMPL=mpich

before_install:
  - sh ./travis/install-mpi.sh $MPI_IMPL

install:
  - |
    if [[ ! -d "build" ]]; then
      mkdir build
    fi
  - export PATH="$HOME/OpenMPI/bin:$PATH"
  - export CC=mpicc
  - export CXX=mpicxx
  - export FC=mpif90
  - cd build; cmake ..; make

script:
  - make test
