language: generic

sudo: required

dist: trusty
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6

env:
  - MPI_IMPL=mpich

before_install:
  - sh ./travis/install-mpi.sh $MPI_IMPL

install:
  - |
    if [[ ! -d "build" ]]; then
      mkdir build
    fi
  - export PATH="$HOME/MPICH/bin:$HOME/OpenMPI/bin:$PATH"
  - export CC=mpicc
  - export CXX=mpicxx
  - export FC=mpif90
  - echo 'Compilers used: '
  - $CC -show
  - $CXX -show
  - $FC -show
  - cd build; cmake ..; make

script:
  - make test
